---
name: Build and Deploy Svelte App to CloudFront
on:
  push:
    branches: [main, feature]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ github.ref == 'refs/heads/main' && 'myorigin-main' || 'myorigin-test' }}
      DIST: build
      REGION: us-east-1
      DIST_ID: E1SMN05OUFXDF7

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::694826974343:role/GithubActionsRole
          role-session-name: myappupdater
          aws-region: ${{ env.REGION }}

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      - name: Install Dependencies
        run: |
          node --version
          npm ci

      - name: Build Static Website
        run: npm run build

      - name: Copy files to the production website with the AWS CLI
        run: |
          # push to either bucket depending on the branch we're on
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
